NBA_DIFF = {'UTA': {'spread': {'overall': {'wins': 1, 'losses': 3, 'push': 0},
                               'home': {'wins': 0, 'losses': 2, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 1, 'under': 2, 'push': 0},
                                   'home': {'over': 0, 'under': 1, 'push': 0},
                                   'away': {'over': 1, 'under': 1, 'push': 0}}},
            'PHX': {'spread': {'overall': {'wins': 4, 'losses': 1, 'push': 0},
                               'home': {'wins': 2, 'losses': 0, 'push': 0},
                               'away': {'wins': 2, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 0, 'under': 4, 'push': 0},
                                   'home': {'over': 0, 'under': 2, 'push': 0},
                                   'away': {'over': 0, 'under': 2, 'push': 0}}},
            'LAC': {'spread': {'overall': {'wins': 4, 'losses': 1, 'push': 0},
                               'home': {'wins': 2, 'losses': 1, 'push': 0},
                               'away': {'wins': 2, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 4, 'under': 2, 'push': -1},
                                   'home': {'over': 1, 'under': 2, 'push': 0},
                                   'away': {'over': 3, 'under': 0, 'push': 0}}},
            'CHI': {'spread': {'overall': {'wins': 2, 'losses': 2, 'push': 0},
                               'home': {'wins': 1, 'losses': 2, 'push': 0},
                               'away': {'wins': 1, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 2, 'under': 1, 'push': 0},
                                   'away': {'over': 0, 'under': 1, 'push': 0}}},
            'NYK': {'spread': {'overall': {'wins': 2, 'losses': 2, 'push': 0},
                               'home': {'wins': 1, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 1, 'under': 1, 'push': 0},
                                   'away': {'over': 1, 'under': 1, 'push': 0}}},
            'SAS': {'spread': {'overall': {'wins': 3, 'losses': 1, 'push': 0},
                               'home': {'wins': 1, 'losses': 1, 'push': 0},
                               'away': {'wins': 2, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 1, 'under': 1, 'push': 0},
                                   'away': {'over': 1, 'under': 1, 'push': 0}}},
            'CHA': {'spread': {'overall': {'wins': 2, 'losses': 2, 'push': 0},
                               'home': {'wins': 1, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 0, 'under': 2, 'push': 0},
                                   'away': {'over': 2, 'under': 0, 'push': 0}}},
            'OKC': {'spread': {'overall': {'wins': 1, 'losses': 1, 'push': 1},
                               'home': {'wins': 0, 'losses': 1, 'push': 1},
                               'away': {'wins': 1, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 1, 'push': 0},
                                   'home': {'over': 2, 'under': 0, 'push': 0},
                                   'away': {'over': 0, 'under': 1, 'push': 0}}},
            'POR': {'spread': {'overall': {'wins': 1, 'losses': 3, 'push': 0},
                               'home': {'wins': 0, 'losses': 2, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 1, 'under': 1, 'push': 0},
                                   'away': {'over': 1, 'under': 1, 'push': 0}}},
            'BKN': {'spread': {'overall': {'wins': 2, 'losses': 3, 'push': 0},
                               'home': {'wins': 1, 'losses': 2, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 1, 'under': 4, 'push': 0},
                                   'home': {'over': 1, 'under': 2, 'push': 0},
                                   'away': {'over': 0, 'under': 2, 'push': 0}}},
            'DET': {'spread': {'overall': {'wins': 1, 'losses': 3, 'push': 0},
                               'home': {'wins': 0, 'losses': 2, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 1, 'under': 1, 'push': 0},
                                   'away': {'over': 1, 'under': 1, 'push': 0}}},
            'PHI': {'spread': {'overall': {'wins': 2, 'losses': 2, 'push': 0},
                               'home': {'wins': 1, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 0, 'under': 4, 'push': 0},
                                   'home': {'over': 0, 'under': 2, 'push': 0},
                                   'away': {'over': 0, 'under': 2, 'push': 0}}},
            'BOS': {'spread': {'overall': {'wins': 3, 'losses': 2, 'push': 0},
                               'home': {'wins': 2, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 3, 'under': 2, 'push': 0},
                                   'home': {'over': 2, 'under': 1, 'push': 0},
                                   'away': {'over': 1, 'under': 1, 'push': 0}}},
            'ATL': {'spread': {'overall': {'wins': 3, 'losses': 1, 'push': 0},
                               'home': {'wins': 0, 'losses': 1, 'push': 0},
                               'away': {'wins': 3, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 1, 'under': 0, 'push': 0},
                                   'away': {'over': 1, 'under': 2, 'push': 0}}},
            'TOR': {'spread': {'overall': {'wins': 0, 'losses': 3, 'push': 0},
                               'home': {'wins': 0, 'losses': 1, 'push': 0},
                               'away': {'wins': 0, 'losses': 2, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 1, 'push': 0},
                                   'home': {'over': 1, 'under': 0, 'push': 0},
                                   'away': {'over': 1, 'under': 1, 'push': 0}}},
            'ORL': {'spread': {'overall': {'wins': 4, 'losses': 0, 'push': 0},
                               'home': {'wins': 1, 'losses': 0, 'push': 0},
                               'away': {'wins': 3, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 4, 'under': 0, 'push': 0},
                                   'home': {'over': 1, 'under': 0, 'push': 0},
                                   'away': {'over': 3, 'under': 0, 'push': 0}}},
            'MIL': {'spread': {'overall': {'wins': 2, 'losses': 3, 'push': 0},
                               'home': {'wins': 1, 'losses': 0, 'push': 0},
                               'away': {'wins': 1, 'losses': 3, 'push': 0}},
                    'over_under': {'overall': {'over': 3, 'under': 2, 'push': 0},
                                   'home': {'over': 1, 'under': 0, 'push': 0},
                                   'away': {'over': 2, 'under': 2, 'push': 0}}},
            'GSW': {'spread': {'overall': {'wins': 1, 'losses': 3, 'push': 0},
                               'home': {'wins': 0, 'losses': 0, 'push': 0},
                               'away': {'wins': 1, 'losses': 3, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 0, 'under': 0, 'push': 0},
                                   'away': {'over': 2, 'under': 2, 'push': 0}}},
            'WAS': {'spread': {'overall': {'wins': 1, 'losses': 3, 'push': 0},
                               'home': {'wins': 0, 'losses': 3, 'push': 0},
                               'away': {'wins': 1, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 2, 'under': 1, 'push': 0},
                                   'away': {'over': 0, 'under': 1, 'push': 0}}},
            'IND': {'spread': {'overall': {'wins': 3, 'losses': 1, 'push': 0},
                               'home': {'wins': 2, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 3, 'under': 1, 'push': 0},
                                   'home': {'over': 2, 'under': 1, 'push': 0},
                                   'away': {'over': 1, 'under': 0, 'push': 0}}},
            'MIN': {'spread': {'overall': {'wins': 2, 'losses': 1, 'push': 1},
                               'home': {'wins': 1, 'losses': 0, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 1}},
                    'over_under': {'overall': {'over': 0, 'under': 4, 'push': 0},
                                   'home': {'over': 0, 'under': 1, 'push': 0},
                                   'away': {'over': 0, 'under': 3, 'push': 0}}},
            'LAL': {'spread': {'overall': {'wins': 3, 'losses': 2, 'push': 0},
                               'home': {'wins': 2, 'losses': 2, 'push': 0},
                               'away': {'wins': 1, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 3, 'push': 0},
                                   'home': {'over': 2, 'under': 2, 'push': 0},
                                   'away': {'over': 0, 'under': 1, 'push': 0}}},
            'MEM': {'spread': {'overall': {'wins': 1, 'losses': 3, 'push': 0},
                               'home': {'wins': 0, 'losses': 2, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 1, 'under': 1, 'push': 0},
                                   'away': {'over': 1, 'under': 1, 'push': 0}}},
            'SAC': {'spread': {'overall': {'wins': 3, 'losses': 1, 'push': 0},
                               'home': {'wins': 2, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 1, 'under': 2, 'push': 0},
                                   'away': {'over': 1, 'under': 0, 'push': 0}}},
            'NOP': {'spread': {'overall': {'wins': 1, 'losses': 3, 'push': 0},
                               'home': {'wins': 0, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 2, 'push': 0}},
                    'over_under': {'overall': {'over': 0, 'under': 4, 'push': 0},
                                   'home': {'over': 0, 'under': 1, 'push': 0},
                                   'away': {'over': 0, 'under': 3, 'push': 0}}},
            'DEN': {'spread': {'overall': {'wins': 1, 'losses': 3, 'push': 0},
                               'home': {'wins': 1, 'losses': 2, 'push': 0},
                               'away': {'wins': 0, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 4, 'under': 0, 'push': 0},
                                   'home': {'over': 3, 'under': 0, 'push': 0},
                                   'away': {'over': 1, 'under': 0, 'push': 0}}},
            'DAL': {'spread': {'overall': {'wins': 1, 'losses': 3, 'push': 0},
                               'home': {'wins': 0, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 2, 'push': 0}},
                    'over_under': {'overall': {'over': 1, 'under': 3, 'push': 0},
                                   'home': {'over': 0, 'under': 1, 'push': 0},
                                   'away': {'over': 1, 'under': 2, 'push': 0}}},
            'MIA': {'spread': {'overall': {'wins': 2, 'losses': 1, 'push': 1},
                               'home': {'wins': 2, 'losses': 0, 'push': 1},
                               'away': {'wins': 0, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 2, 'push': 0},
                                   'home': {'over': 1, 'under': 2, 'push': 0},
                                   'away': {'over': 1, 'under': 0, 'push': 0}}},
            'HOU': {'spread': {'overall': {'wins': 1, 'losses': 2, 'push': 0},
                               'home': {'wins': 0, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 1, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 0, 'push': 0},
                                   'home': {'over': 0, 'under': 0, 'push': 0},
                                   'away': {'over': 2, 'under': 0, 'push': 0}}},
            'CLE': {'spread': {'overall': {'wins': 3, 'losses': 1, 'push': 0},
                               'home': {'wins': 2, 'losses': 1, 'push': 0},
                               'away': {'wins': 1, 'losses': 0, 'push': 0}},
                    'over_under': {'overall': {'over': 2, 'under': 3, 'push': -1},
                                   'home': {'over': 1, 'under': 3, 'push': 0},
                                   'away': {'over': 1, 'under': 0, 'push': 0}}}}
